# Generated by Django 4.0.1 on 2022-02-14 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_staffprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='StaffProfile',
        ),
        migrations.DeleteModel(
            name='StudentProfile',
        ),
    ]
