# Generated by Django 4.0.1 on 2022-02-23 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='rf_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
