# Generated by Django 4.0.1 on 2022-01-22 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcopies',
            name='is_book_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='bookcopies',
            name='is_book_lost',
            field=models.BooleanField(default=False),
        ),
    ]
