# Generated by Django 4.0.1 on 2022-02-15 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_lendbook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='books.bookcopies'),
        ),
    ]
