# Generated by Django 4.0.1 on 2022-02-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_alter_lendbook_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendbook',
            name='is_return',
            field=models.BooleanField(default=False),
        ),
    ]
