# Generated by Django 4.0.1 on 2022-02-21 05:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_lendbook_is_return'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_dash', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='requestbook',
            unique_together={('books', 'user', 'req_date')},
        ),
    ]
